spring:
  datasource:
    url: jdbc:mysql://localhost:3306/bollaemallae?serverTimezone=Asia/Seoul
    username: root
    password: arirang0821!

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
tmdb:
  api-key: ed1e283558c0fce1ab438c64c7495a86
  base-url: https://api.themoviedb.org/3